### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by fabaff** [meauxt/socialbladeclient#1]
Please add a timeout to the [request](https://github.com/meauxt/socialbladeclient/blob/master/socialbladeclient/__init__.py#L15). Thanks

**Comment by meauxt** [comment]
@fabaff missed the notifiation for this issue :( sorry man

**Comment by meauxt** [comment]
@pinkywafer  took care of it i just create the release and ready to be consumed

**Comment by pinkywafer** [comment]
if you can, that'd be great.  Thanks
