### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by pinkywafer** [meauxt/socialbladeclient#4]
When will the updates be released to pypi?  I believe it will be version 0.3?
Thanks

**Comment by meauxt** [comment]
0.3 just release :) it's in pypi!
do you want to create Homeassistant PR or you want me to ?

**Comment by pinkywafer** [comment]
if you can, that'd be great. Thanks

**Comment by meauxt** [comment]
sure! i will do it over this week!

**Comment by pinkywafer** [comment]
Just FYI: I have had some time today, so have submitted the Home Assistant PR to update to latest version home-assistant/home-assistant#32191
