### ISSUE TITLE
Convert subscriber count to integer

### ISSUE THREAD

**Issue by aaronpk** [meauxt/socialbladeclient#5]
Socialblade shows an estimated subscriber count because that's what YouTube provides, such as "1K" or "2.2M". It would be great if this client could convert that to an actual number so that it would be easier to integrate with things that expect to be able to compare numbers and such.

**Comment by meauxt** [comment]
valid ask to handle it as number in automation, am adding it as additional property so it wont break current flow

**Comment by meauxt** [comment]
it's published to pypi as version 0.4
https://pypi.org/project/socialbladeclient/0.4/
